version: "2"
services:
    plex:
      image: plexinc/pms-docker
      container_name: plex
      volumes:
        - ${MEDIA_DIR}/movies:/data/movies
        - ${MEDIA_DIR}/tv:/data/tv
        - ${MEDIA_DIR}/music:/data/music
        - ${CONFIG_DIR}/plex:/config
        - /var/transcode:/transcode
      restart: unless-stopped
      network_mode: "host"
    plexpy:
      image: tautulli/tautulli
      container_name: plexpy
      volumes:
        - ${CONFIG_DIR}/plexpy:/config
        - ${CONFIG_DIR}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs/:/plex_logs:ro
      restart: unless-stopped
      ports:
        - 8181:8181
    sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      volumes:
        - ${CONFIG_DIR}/sonarr:/config
        - ${MEDIA_DIR}/tv:/tv
        - /etc/localtime:/etc/localtime:ro
        - ${MEDIA_DIR}/download/complete:/downloads
      restart: unless-stopped
      ports:
        - 8989:8989
    radarr:
       image: linuxserver/radarr
       container_name: radarr
       volumes:
        - ${CONFIG_DIR}/radarr:/config
        - ${MEDIA_DIR}/movies:/movies
        - /etc/localtime:/etc/localtime:ro
        - ${MEDIA_DIR}/download/complete:/downloads
       restart: unless-stopped
       ports:
        - 7878:7878
    sabnzbd:
      image: linuxserver/sabnzbd
      container_name: sabnzbd
      volumes:
        - ${CONFIG_DIR}/sabznbd:/config
        - ${MEDIA_DIR}/download/incomplete:/download/incomplete
        - ${MEDIA_DIR}/download/complete:/download/complete
      ports:
        - 8080:8080
      restart: unless-stopped
