version: "3"
services:
    share:
      image: dperson/samba
      container_name: samba
      volumes:
        - /mnt/tub:/mount
      ports:
        - 139:139
        - 445:445
      restart: always
    dashboard:
      image: linuxserver/heimdall
      container_name: heimdall
      volumes:
        - /mnt/tub/config/heimdall:/config 
      ports:
        - 80:80
        - 443:443
      restart: always
    plex:
      image: plexinc/pms-docker
      container_name: plex
      volumes:
        - /mnt/tub/data/movies:/data/movies
        - /mnt/tub/data/tv:/data/tv
        - /mnt/tub/data/music:/data/music
        - /mnt/tub/config/plex:/config
        - /mnt/tub/data/transcode:/transcode
      restart: unless-stopped
      network_mode: "host"
    updates:
      image: v2tec/watchtower
      container_name: watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      restart: always
      command: --interval 30
    management:
      image: portainer/portainer
      container_name: portainer
      volumes:
        - /mnt/tub/config/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
      restart: always
    
