version: "2"
services:
    dashboard:
      image: linuxserver/heimdall
      container_name: heimdall
      volumes:
        - /home/$USER/tvbox/config/heimdall:/config 
      ports:
        - 80:80
      restart: always
    plex:
      image: plexinc/pms-docker
      container_name: plex
      volumes:
        - /opt/tvbox/movies:/data/movies
        - /opt/tvbox/tv:/data/tv
        - /opt/tvbox/music:/data/music
        - /home/$USER/tvbox/config/plex:/config
        - /home/$USER/tvbox/data/transcode:/transcode
      restart: unless-stopped
      network_mode: "host"
    plexpy:
      image: tautulli/tautulli
      container_name: plexpy
      volumes:
        - /home/$USER/tvbox/config/plexpy:/config
        - /home/$USER/tvbox/config/plex/Library/Application\ Support/Plex\ Media\ Server/Logs/:/plex_logs:ro
      restart: unless-stopped
      ports:
        - 8181:8181
    sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      volumes:
        - /home/$USER/tvbox/config/sonarr:/config
        - /opt/tvbox/tv:/tv
        - /etc/localtime:/etc/localtime:ro
        - /opt/tvbox/download/complete:/downloads
      restart: unless-stopped
      ports:
        - 8989:8989
    radarr:
       image: linuxserver/radarr
       container_name: radarr
       volumes:
        - /home/$USER/tvbox/config/radarr:/config
        - /opt/tvbox/movies:/movies
        - /etc/localtime:/etc/localtime:ro
        - /opt/tvbox/download/complete:/downloads
       restart: unless-stopped
       ports:
        - 7878:7878
    sabnzbd:
      image: linuxserver/sabnzbd
      container_name: sabnzbd
      volumes:
        - /home/$USER/tvbox/config/sabznbd:/config
        - /opt/tvbox/download/incomplete:/downloads/incomplete
      ports:
        - 8080:8080
      restart: unless_stopped
    updates:
      image: v2tec/watchtower
      container_name: watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      restart: always
      command: --interval 30
    management:
      image: portainer/portainer
      container_name: portainer
      volumes:
        - /home/$USER/tvbox/config/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 9000:9000
      restart: always
