version: "3"
services:
    share:
      image: dperson/samba
      container_name: samba
      volumes:
        - /mnt/tub:/mount
      ports:
        - 139:139
        - 445:445
      restart: always
    dashboard:
      image: linuxserver/heimdall
      container_name: heimdall
      volumes:
        - /mnt/tub/config/heimdall:/config 
      ports:
        - 80:80
        - 443:443
      restart: always
    plex:
      image: plexinc/pms-docker
      container_name: plex
      volumes:
        - /mnt/tub/data/movies:/data/movies
        - /mnt/tub/data/tv:/data/tv
        - /mnt/tub/data/music:/data/music
        - /mnt/tub/config/plex:/config
        - /mnt/tub/data/transcode:/transcode
      restart: unless-stopped
      network_mode: "host"
    plexpy:
      image: tautulli/tautulli
      container_name: plexpy
      volumes:
        - /mnt/tub/config/plexpy:/config
        - /mnt/tub/config/plex/Library/Application\ Support/Plex\ Media\ Server/Logs/:/plex_logs:ro
      restart: unless-stopped
      ports:
        - 8181:8181
    sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      volumes:
        - /mnt/tub/config/sonarr:/config
        - /mnt/tub/data/tv:/tv
        - /etc/localtime:/etc/localtime:ro
        - /mnt/tub/data/download/sabnzbd/complete/tv:/downloads
      restart: unless-stopped
      ports:
        - 8989:8989
    couchpotato:
      image: linuxserver/couchpotato
      container_name: couchpotato
      volumes:
        - /mnt/tub/config/couchpotato:/config
        - /mnt/tub/data/movies:/movies
        - /mnt/tub/data/download/sabnzbd/complete/movies:/downloads
      restart: unless-stopped
      ports:
        - 5050:5050
    sabnzbd:
      image: linuxserver/sabnzbd
      container_name: sabnzbd
      volumes:
        - /mnt/tub/config/sabnzbd:/config
        - /mnt/tub/data/download/sabnzbd/incomplete:/incomplete-downloads
        - /mnt/tub/data/download/sabnzbd/complete:/downloads
      restart: unless-stopped
      ports:
        - 9090:9090
    deluge:
      image: linuxserver/deluge
      container_name: deluge
      volumes:
        - /mnt/tub/config/sabnzbd:/config
        - /mnt/tub/data/download/deluge/incomplete:/downloads
        - /mnt/tub/data/download/deluge/complete:/complete
        - /mnt/tub/data/blackhole:/blackhole
      restart: unless-stopped
      ports:
        - 8112:8112
    updates:
      image: v2tec/watchtower
      container_name: watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      restart: always
      command: --interval 30
    management:
      image: portainer/portainer
      container_name: portainer
      volumes:
        - /mnt/tub/config/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 9000:9000
      restart: always
    
